### ISSUE TITLE
Why are we loading Poppins font on every page ? Is there a way to import it once ?

### ISSUE THREAD

**Issue by faran4engg** [NextGenDevOrg/sobiya-html-css-Ecommerce-website#1]
cc: @fayez-baig @Tauqeer-Ahmed-99 @Tanvir04khan @rifaq-ahmer @syedabdullahali @muzeeb100

**Comment by faran4engg** [comment]
LGTM 👍🏼 This issue can be closed !

**Comment by sobiiya** [comment]
I already remove it from all html pages
